### ISSUE TITLE
Simplify NestedSet::__construct

### ISSUE THREAD

**Issue by guilhermeaiolfi** [bartko-s/stefano-tree#14]
Although it says in the README that it doesn't have any dependencies, the way it's today, it needs Doctrine and Zend\Db. It needs to be installed to be able to use the ```NestedSet``` class. I think that class only needs to get an instance of an ```AdapterInterface``` and everything else should be handled outside of this class.

What do you think?

**Comment by bartko-s** [comment]
Hi @guilhermeaiolfi . No doctrine-dbal, zend1 or zend2 is not required. Library works without this dependencies. Probably you do something wrong.
