### ISSUE TITLE
A Typical Data Field and Value for a Node

### ISSUE THREAD

**Issue by philecom** [bartko-s/stefano-tree#15]
I've been trying to integrate this library into Joomla components.
My actual struggle is; for an example taking the following code from the documentation:

   ` try {
       $data = array(
        // values
        // id_column_name => uuid 
       ); 

     // create root node.
     $rootNodeId = $tree->createRootNode($data);  
     // create root node. Second param "$scope" is required only if scope support is enabled.
     $rootNodeId = $tree->createRootNode($data, $scope);    
     } catch (ValidationException $e) {
     $errorMessage = $e->getMessage();
      } `

 what is going to be the values for this section
`    $data = array(
        // values
        // id_column_name => uuid 
    );`

if my database table has these columns
      `	'tableName' => 'vz0q4_users',
	'idColumnName' => 'id',
	'sequenceName' => 'categories',
	'scopeColumnName' => 'scope',
	'leftColumnName' => 'lft',
	'rightColumnName' => 'rght',
	'levelColumnName' => 'level',
	'parentIdColumnName' => 'parent_id'
   `

Thank you.

**Comment by philecom** [comment]
@bartko-s I'm using MySQL(MariaDB)
I'm using autoincrement as a primary key
I'm currently inserting into one tree; but would be happy to know how to insert into multiple independent tree structure

**Comment by bartko-s** [comment]
Then:
- remove 'sequenceName' from your settings. This is necessary only for postgres(sequence)
- remove 'scopeColumnName' from your settings. This is used only when your want to have more then one tree in one DB table. see #6
- When you create new node then remove 'id' from params. "id" primary key will be generated by database(autoincrement)
```
$options = array(
    'tableName' => 'vz0q4_users',
    'idColumnName' => 'id', 
    'leftColumnName' => 'lft',
    'rightColumnName' => 'rght',
    'levelColumnName' => 'level',
    'parentIdColumnName' => 'parent_id'
);

$tree = new NestedSet($options, $dbAdapter);
```

**Comment by philecom** [comment]
@bartko-s 
I got that part. what my issue is the content of "values" in the $data array

 `$data = array( 
    // values 
    // id_column_name => uuid
   );

   $rootNodeId = $tree->createRootNode($data);
 `

**Comment by philecom** [comment]
@bartko-s I dont know why you close this issue when the problem has not been solved

**Comment by bartko-s** [comment]
This is not issue. This is only question.  The content of $data is values which you want to insert into database row exlude primary_key(is generated by database autoincrement), left, right, level, scope, parent_id. See [example](https://github.com/bartko-s/stefano-tree/blob/master/examples/ex1.php)
