### ISSUE TITLE
Do you have a full list of BC breaks?

### ISSUE THREAD

**Issue by linaori** [bartko-s/stefano-tree#19]
I'm trying to upgrade from 2.x to 4.x and I can't find any BC breaks before 3.1 unless I search through all revisions of the update file. Is there a summary I can find somewhere? Right now I fail properly upgrading due to the lack of BC break documentation and what the replacement of those functions should be.

**Comment by bartko-s** [comment]
BC break list from 2.x to 3.x does not exists.

**Comment by linaori** [comment]
Do you have any pointers I can use when upgrading? I managed to find some references in old commits what actually changed, but I'm not exactly sure how to use them. It's primarily around examples of removed functions from the `NestedSet`

**Comment by bartko-s** [comment]
@linaori  [Here](https://github.com/bartko-s/stefano-tree/blob/master/examples/ex1.php) is working example how to use new version.

**Comment by linaori** [comment]
That won't help me sadly, I need to know how to exactly call the new signatures compared to the old ones, so the end-result is the same.
