### ISSUE TITLE
Add support for user defined node ID

### ISSUE THREAD

**Issue by bartko-s** [bartko-s/stefano-tree#9]
Library supports only auto generated node  ID (sequence, auto increment). Add support for user defined id (uuid, ...).

**Comment by TNAJanssen** [comment]
Do you need help with this, i tried using UUID but it converts it to int

**Comment by bartko-s** [comment]
@TNAJanssen - I implemented it (develop branch). Can you test it before I release new version?

**Comment by TNAJanssen** [comment]
@bartko-s We are still in the process of upgrading to PHP7.2, and are stuck on PHP7.0 at the moment so i can't use the 3.x version yet!

**Comment by bartko-s** [comment]
Library support only php 7.1 and above. Time to upgrade your codebase :)
